permalink: pretty
rdiscount:
extensions: [smart]

gems:
  - jekyll-sitemap

name: MyLittleIT Blog
url: https://blog.mylittleit.fr
description: Le blog de l'équipe IT My Little Paris
twitter: My_Little_Paris
