permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: IT Blog
url: http://blog.mylittleit.fr
description: A fantastic blog that is fantastic.
twitter: My_Little_Paris
